version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000
    networks:
      - js-develop

  db:
    image: mysql:latest
    container_name: js-database
    restart: always
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3306:3306"
    volumes:
      - database-data:/usr/src/data
    networks:
      - js-develop
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=12345 --execute \"Select 1;\""
      interval: 20s
      timeout: 70s
      retries: 3

  backend:
    image: backend
    build:
      context: ./backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      MYSQL_HOST: "db"
      #      DATABASE_HOST: "db"
      JWT_SECRET_TOKEN: "token"
      CORS_ORIGIN_REGEX: "http([s])?:\/\/localhost:3001"
      BACKEND_START_COMMAND: "npm run start"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - js-develop
    volumes:
      - backend-data:/usr/src/data

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - backend
    environment:
      SERVER_ORIGIN: "backend"
      NODE_ENV: "development"
      FRONTEND_START_COMMAND: "npm run build"
    networks:
      - js-develop
#    healthcheck?
volumes:
  database-data:
  backend-data:

networks:
  js-develop:
